### PR TITLE
v1.0.9-r4: use major-major upper bounds only

### PR DESCRIPTION
**Pull request by andreasabel**
Optimistic strategy: assume that nothing breaks if dependencies bump
their major version (unless they bump the major-major version).

Breakage can then be addressed by Hackage revisions.

### CODE REVIEW

**Comment by Bodigrim** [comment]
It would be nice to revise `cabal-doctest` on Hackage, otherwise [plenty of packages](https://packdeps.haskellers.com/reverse/cabal-doctest) are blocked from upgrade to GHC 9.10.

**Comment by ulidtko** [comment]
Hi @andreasabel!  I've fixed the CI for GHC 9.10. We're ready for revision 4 here.

(Per #79, repo transfer was done today; I'd appreciate if you let me upload the revision myself, to get practice)

I'm happy with major-major bounds in the examples / tests — but in the main lib, I'm reverting to `Cabal < 3.14`. This feels more uniform, in-line with previous revisions, and I don't feel confident enough (in Cabal as a dependency) to break the pattern just yet.

**Comment by Qqwy** [comment]
Looking forward to the new version release!

**Comment by Bodigrim** [comment]
@phadej could you possibly add @ulidtko to maintainers? https://hackage.haskell.org/package/cabal-doctest/maintainers/

**Comment by andreasabel** [comment]
> could you possibly add @ulidtko to maintainers? [hackage.haskell.org/package/cabal-doctest/maintainers](https://hackage.haskell.org/package/cabal-doctest/maintainers/)

Done!

**Comment by ulidtko** [comment]
Thanks @andreasabel :pray: 

I'm going to merge this, but will actually release another version, rather than a metadata revision. Because there was a code change in 009a688d7bffc8df368c51b46ca553cd15e23440 — albeit small, strictly speaking it steps beyond applicability of hackage revisions mechanism, IIUC.

**Pull request merged**
